{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": "select * from rawdata" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  InternalPumpLeakage\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prediction 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CoolerCondition, ValveCondition, InternalPumpLeakage, HydraulicAccumulator, StableFlag\nFROM metrics_predict15\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ValveCondition\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  HydraulicAccumulator\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  StableFlag\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CoolerCondition\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM rawdata\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  vs1\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volume Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  FS1,FS2\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  TS1,TS2,TS3,TS4\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CE,CP,SE\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Predicted Panel",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CoolerCondition, ValveCondition, InternalPumpLeakage, HydraulicAccumulator, StableFlag\nFROM metrics_predict15\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "  SELECT\n  \"timestamp\" AS \"time\",\n  CoolerCondition, ValveCondition, InternalPumpLeakage, HydraulicAccumulator, StableFlag\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Pressure Sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  PS1,PS2,PS3,PS4,PS5,PS6\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Vibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  vs1\nFROM sensor_data\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SensorData",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM rawdata\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}